version: "3.9"

services:
  postgres:
    image: postgres:17.6
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      retries: 5
    command: ["postgres", "-c", "max_prepared_transactions=16"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: information-security-lab-1/api:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - local
    environment:
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: ${PG_DATABASE}
      PG_POOL_SIZE: ${PG_POOL_SIZE}

      LOG_LOCATION: ${LOG_LOCATION}
      DEBUG: ${DEBUG}
      APP_PORT: ${APP_PORT}

      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_PORT}/healthcheck" ]
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  postgres-storage:

networks:
  local: